### PR TITLE
Handle Songbooks (#2)

### PR DESCRIPTION
**Pull request by gorgobacka**
The changes were much easier than expected. Therefore, here is the PR for #2.

Example 1 (Songbook):
```yaml
# content of The_Big_Book_of_Jazz.yml
path: The_Big_Book_of_Jazz.pdf
artist: Various Artists
title: The Big Book of Jazz
songs:
    - artist: Artist 1
      title: Song 1
      pages: [2, 3]
    - artist: Artist 2
      title: Song 2
      pages: [4, 5, 6, 5, 6]
    - artist: Various Artists
      title: The Big Book of Jazz (Full book)
```

Example 2 (single sheet):
```yaml
# content of Let_it_be.yml
path: Let_it_be.pdf
artist: The Beatles
title: Let It Be
```

Here is how it works currently:

- Each mentioned song is added to the Sheet list. (Example 1)
- If no song information is provided, the head (artist and title) is used for the sheet. (Example 2)
- If no page information is used, the complete pdf is used. (Example 1: Song 3, Example 2)

The new functionality can be activated with the parameter `--parse-yaml`. The precious functionality (parsing PDF files) can be activated with the parameter `--parse-pdf`. Both functionalities can be used at the same time. (Maybe it's better to have a parameter to deactivate PDF parsing, instead of activating it. Then this implementation is completely backwards compatible.)

What is currently not working:

- Uploading of yaml files
- Good error handling (e.g. incorrect page numbers)
- Do not parse pdf files twice (as raw pdf and in yaml file)
- The book title and book artist is currently not used. But I think about displaying it and including it into the search.

What do you think?

### CODE REVIEW

**Comment by PatWie** [comment]
Hi

I will have a more detailed look at it. I do not think that it is necessary to introduce 2 new flags. Why not excluding all pdfs that have been referenced in a yaml file?

**Comment by gorgobacka** [comment]
> Why not excluding all pdfs that have been referenced in a yaml file?

But I agree, it's better to have only one flag. In the beginning, it was my plan to skip pdfs included in the yaml. But then I read that Go has no build-in functionality to check, if an item is in an array. Therefore, I skipped it for now, till I got feedback for the overall implementation.

**Comment by gorgobacka** [comment]
Do you have any suggestions for the overall implementation or can I continue to address the parts that are not working right now?

**Comment by PatWie** [comment]
Honestly I haven't had time to check and test it yet. But overall it looks fine to me!

**Comment by gorgobacka** [comment]
Ok, no problem. Then I will continue to solve the remaining tasks to finalize this PR.

PS: I'm already using this implementation locally. :)

**Comment by gorgobacka** [comment]
Oh... I still need to finalize this PR. I will try to get it done soon.

**Comment by gorgobacka** [comment]
> I do not think that it is necessary to introduce 2 new flags. Why not excluding all pdfs that have been referenced in a yaml file?

I updated the code and remove the second flag. Now there is only one flag `--parse-yaml` to activate the new functionality. Referenced PDFs are automatically excluded from normal processing.

Additionally, I described the new functionality in the README. But I'm not sure, if it's clear enough.

Please let me know what you think.

**Comment by gorgobacka** [comment]
@PatWie Can you please check this PR? I think it's finished.

**Comment by gorgobacka** [comment]
@PatWie ping

**Comment by gorgobacka** [comment]
Thank you.

**Pull request merged**
